-- Create artists Table --
CREATE TABLE artists (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    mobile VARCHAR(50) UNIQUE NOT NULL,
    city VARCHAR(50) NOT NULL,
    gender VARCHAR(20),
    age INT NOT NULL,
    qualification VARCHAR(150),
    category VARCHAR(50) NOT NULL,
    yearExp VARCHAR(50) NOT NULL,
    certification VARCHAR(255),
    brand_name VARCHAR(255) NOT NULL,
    local_gallery boolean NOT NULL,
    made_courses VARCHAR(100) NOT NULL,
    avatar VARCHAR(255),
    facebook VARCHAR(255) NOT NULL,
    instagram VARCHAR(255),
    youtube VARCHAR(255),
    website VARCHAR(255),
    artist boolean NOT NULL DEFAULT true,
    preview boolean DEFAULT false,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);